images:
- name: docker.io/redis
  newTag: "7.0.8"

namespace: usdf-kafka

resources:
- ns.yaml
- redis-deploy.yaml
- strimzi-0.35.1.yaml
- kafka-persistent.yaml

secretGenerator:
- name: redis
  files:
  - redis-password=etc/.secrets/redis
